import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { toUpper } from 'lodash';

const inter = Inter({ subsets: ['latin'] });
const str = toUpper('hello');

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang='en'>
      {str}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
