import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { lala } from 'ui/card';
// import { toUpper } from 'lodash';

const inter = Inter({ subsets: ['latin'] });

// const str = toUpper('hello');

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turb',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  const haha = lala.map(x => <p key={x}>{x} </p>);
  return (
    <html lang='en'>
      {haha}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
